name: 📚 Documentation
description: Report issues with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "good first issue", "needs triage", "help wanted"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve TorchEBM's documentation!

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this documentation issue hasn't been reported before
          required: true
        - label: I have checked the latest documentation on the website
          required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - "Missing Documentation"
        - "Incorrect/Outdated Information"
        - "Unclear Explanation"
        - "Broken Links"
        - "Typo/Grammar"
        - "Missing Examples"
        - "API Documentation"
        - "Tutorial/Guide Request"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: documentation-section
    attributes:
      label: Documentation Section
      description: Which part of the documentation needs attention?
      options:
        - "Getting Started Guide"
        - "API Reference"
        - "Tutorials"
        - "Examples"
        - "Developer Guide"
        - "FAQ"
        - "Installation Instructions"
        - "Energy Functions Guide"
        - "Samplers Guide"
        - "Loss Functions Guide"
        - "Visualization Guide"
        - "README"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: current-documentation
    attributes:
      label: Current Documentation
      description: Link to the specific documentation page or section that needs improvement
      placeholder: |
        - URL: https://...
        - Section: "Energy Functions > Custom Functions"
        - File: docs/guides/energy_functions.md
        - Line numbers (if applicable): 45-60
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what's wrong with the current documentation or what's missing
      placeholder: |
        - What information is missing, incorrect, or unclear?
        - What confused you when reading the documentation?
        - What questions weren't answered?
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        - What information should be added?
        - How should existing content be clarified?
        - What examples would be helpful?
        - What structure changes would improve understanding?
    validations:
      required: true

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Content
      description: If you have specific text, examples, or content to suggest, please include it here
      placeholder: |
        You can include:
        - Proposed text changes
        - Code examples
        - Diagrams or illustrations (describe them)
        - Links to helpful resources

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit most from this documentation improvement?
      multiple: true
      options:
        - "Beginners to EBMs"
        - "Experienced ML practitioners"
        - "PyTorch users"
        - "Researchers"
        - "Students"
        - "Contributors/Developers"
        - "All users"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - "Low - Minor improvement"
        - "Medium - Helpful addition"
        - "High - Important for user success"
        - "Critical - Blocking user understanding"
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the scenario where this documentation issue affects users
      placeholder: |
        "As a [type of user], I was trying to [accomplish task] when I [encountered issue]. 
        I expected to find [information] but instead [what happened]. 
        This would be solved by [proposed solution]."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help improve this documentation?
      options:
        - label: I would be willing to write/edit the documentation
        - label: I can provide examples or code snippets
        - label: I can review proposed changes
        - label: I can help with testing the documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help improve the documentation
      placeholder: |
        - Screenshots of confusing sections
        - Links to related discussions or issues
        - Examples from other projects
        - References to research papers or external resources

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
