name: ❓ Question
description: Ask a question about using TorchEBM
title: "[Question]: "
labels: ["question", "help wanted", "needs triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! We're here to help you get the most out of TorchEBM.
        
        **Before asking:** Please check if your question has already been answered in:
        - [Documentation](https://your-docs-url.com)
        - [FAQ](https://your-docs-url.com/faq)
        - [Existing issues and discussions](https://github.com/your-repo/issues)

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have read the relevant documentation
          required: true
        - label: I have tried to solve this myself first
          required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What area does your question relate to?
      options:
        - "Getting Started"
        - "Energy Functions"
        - "Samplers (HMC, Langevin, etc.)"
        - "Loss Functions"
        - "Model Training"
        - "Datasets"
        - "Visualization"
        - "Performance/Optimization"
        - "Integration with other libraries"
        - "Theory/Mathematical concepts"
        - "Installation/Setup"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible. Include what you're trying to achieve and what's unclear.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're working on
      placeholder: |
        - What are you trying to build or accomplish?
        - What's your background with EBMs or PyTorch?
        - What have you tried so far?
        - Where did you get stuck?

  - type: textarea
    id: code-example
    attributes:
      label: Code Example (if applicable)
      description: If your question involves code, please provide a minimal example
      render: python
      placeholder: |
        import torch
        import torchebm
        
        # Your code here
        # Include any relevant setup, data, or operations

  - type: textarea
    id: current-approach
    attributes:
      label: What You've Tried
      description: What approaches have you already attempted?
      placeholder: |
        - Code you've written
        - Documentation you've read
        - Other solutions you've tried
        - Results of your attempts

  - type: dropdown
    id: experience-level
    attributes:
      label: Experience Level
      description: What's your experience level with the relevant technologies?
      options:
        - "Beginner - New to EBMs and/or PyTorch"
        - "Intermediate - Some experience with EBMs or PyTorch"
        - "Advanced - Experienced with EBMs and PyTorch"
        - "Expert - Very experienced, working on advanced use cases"

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What do you expect or hope to achieve?
      placeholder: |
        - What should the result look like?
        - What behavior are you expecting?
        - What would success look like for your use case?

  - type: textarea
    id: system-info
    attributes:
      label: System Information (if relevant)
      description: Include system details if they might be relevant to your question
      placeholder: |
        - TorchEBM version: 
        - PyTorch version: 
        - Python version: 
        - Operating system: 
        - Hardware (CPU/GPU): 

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is getting an answer to this question?
      options:
        - "Low - Just curious"
        - "Medium - Would help my project"
        - "High - Blocking my progress"
        - "Critical - Urgent deadline"

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might help us answer your question
      placeholder: |
        - Links to related resources
        - Screenshots or diagrams
        - Error messages (if any)
        - Specific requirements or constraints

  - type: checkboxes
    id: follow-up
    attributes:
      label: Follow-up
      description: How can we help you best?
      options:
        - label: I would appreciate a detailed explanation
        - label: I would like code examples
        - label: I would like links to relevant documentation
        - label: I would be interested in contributing documentation about this topic

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
